---
- hosts: localhost

  tasks:

    - name: "run container"
      docker_container:
        name: "spring_app"
        image: "shurand/jenkins-test:8"
        exposed_ports:
          - 9090
        env:
          POSTGRESQL_HOST: "172.17.0.1"
          POSTGRESQL_PORT: "15432"
        state: started

...